### ISSUE TITLE
Terminology - VR mode?

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#1]
https://github.com/gusmanb/PSVRFramework/blob/master/PSVRFramework/PSVR.cs#L442

Do you mean 'Cinematic' mode, as termed by Sony? To me VR mode is full, PC renders world...
Simon.

**Comment by gusmanb** [comment]
With VR mode I refer to direct video from computer, not cinematic mode.

I should normalize the names in a near future (I did all that on a 24 hours rush and my head thought it was funny to change names without my permission).

**Comment by gusmanb** [comment]
Closing as the code now has the correct names.
