### ISSUE TITLE
Test app with LibUSB and Linux

### ISSUE THREAD

**Issue by gusmanb** [gusmanb/PSVRFramework#11]
@mungewell One doubt, are you using the toolbox under linux? If yes, does it works fine?

As I'm re-enabling LibUSB support would be great if the tool is portable between Linux and Windows, the library I use claims to be compatible, but there are some special classes for mono, so I'm not sure if the high level classes already choose which underliying classes to use correctly or I must add some code to enable it's support.

**Comment by mungewell** [comment]
I've only tried it under Windows10. I don't have Mono on my Linux machine and am a little bandwidth limited through the week (work away from home and only have a cell plan to keep me connected during the evenings).

Can you detail which Mono packages you think I might need, and I can 'sneaker-net' them from work.
http://packages.ubuntu.com/search?keywords=mono&searchon=names&suite=yakkety&section=all

Simon.
PS. I support the move back to LibUSB as I'd like to keep hacking away in python ;-)

**Comment by gusmanb** [comment]
@mungewell yeah, the WinUSB has brought more problems than other thing, I just published the new release with support for both, hope this helps people to get it working, also I'm going to check again native com, I think I know why I could not get the device to properly work using the driver which Windows installed.

To check the toolbox you will need mono-complete V4.4 or higher and libgdiplus, here are the instructions to add the repos and keys: http://www.mono-project.com/docs/getting-started/install/linux/

If you're tempted to install the packages from the os distro don't do it, all the distros use extremely old (5+ years) releases and they're a mess.

I will try to get a bit of time and get up a VM with linux, but I'm not very confident about if the USB will work as expected, I had some time a go a nightmare with vbox and USB's

**Comment by mungewell** [comment]
err too late, I installed the following on top of Xubuntu live-CD
> libmono-corlib4.5-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> mono-runtime_4.2.1.102+dfsg2-7ubuntu4_amd64.deb
> libmono-security4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-configuration4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-xml4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> mono-4.0-gac_4.2.1.102+dfsg2-7ubuntu4_all.deb
> mono-gac_4.2.1.102+dfsg2-7ubuntu4_all.deb
> mono-runtime-common_4.2.1.102+dfsg2-7ubuntu4_amd64.deb
> mono-runtime-sgen_4.2.1.102+dfsg2-7ubuntu4_amd64.deb
> libmono-system-security4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libgdiplus_4.2-1ubuntu2_amd64.deb
> libmono-accessibility4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-data-tds4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-i18n4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-i18n-west4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-posix4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-core4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-data4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-drawing4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-enterpriseservices4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-numerics4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-runtime-serialization4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-runtime-serialization-formatters-soap4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-servicemodel-internals0.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-transactions4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-system-windows-forms4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb
> libmono-webbrowser4.0-cil_4.2.1.102+dfsg2-7ubuntu4_all.deb

Which got me 'running', up to the attached error message: 
[psvr_broken.txt](https://github.com/gusmanb/PSVRFramework/files/570455/psvr_broken.txt)
> Unhandled Exception:
> System.EntryPointNotFoundException: SetWindowsHookEx

**Comment by gusmanb** [comment]
@mungewell Ow. ok, ver. 4.2 is not too old, seems that Ubuntu has updated
the packages (finally! XD). I know why this error happened, I use a global
hook library to catch the hotkeys and it uses native calls, I will check
the os where the app is running and disable it.

Thanks for the test :D

2016-11-04 2:49 GMT+01:00 mungewell <notifications@github.com>:

**Comment by gusmanb** [comment]
Closing as the testing should be done with the new package posted on issues.
