### ISSUE TITLE
Test package with new drivers

### ISSUE THREAD

**Issue by gusmanb** [gusmanb/PSVRFramework#12]
I've created an installer for the app and installers for the LibUSB and WinUSB drivers. Also I need some tests under Linux, this package has the hotkeys disabled to avoid crashes.

Anybody testing the new installers please report on this issue:

* OS version
* Previously installed versions if any
* PSVRTool installation results
* WinUSB installation results
* LibUSB installation results

Steps to install drivers:

1-Uncompress the DriverPackages ZIP file
2-Choose which driver to install, LibUSB or WinUSB and enter in it's folder
3-Enter to PS_VR_Control_Interface_5 and execute InstallDriver
4-Repeat the same process for folder PS_VR_Sensor_Interface_4

[PSRToolboxSetup.zip](https://github.com/gusmanb/PSVRFramework/files/570603/PSRToolboxSetup.zip)
[DriverPackages.zip](https://github.com/gusmanb/PSVRFramework/files/570604/DriverPackages.zip)

**Comment by klimmiks** [comment]
Win 10 1607 - I had tried to install filters previously, which apparently had worked, but could not get the tool to run, I have since removed the filters. 

Ran the WinUSB first - installed fine. Restarted and tested with PSVRTool (also installed fine) - PSVRTool ran fine except for any VR mode. Cinematic ran fine, all sliders worked. Testing with LibUSB soon.

**Comment by tzwientjuh** [comment]
Windows 10 1607here
Drivers installed with succes. Libusb and winusb works.
psvrtool is installed and working but when exiting, there's an error and it had to hard exit.

psvrtool without install works fine.

**Comment by Donlurchio** [comment]
Windows 10 1607

have installed winusb driver and psvrtool. Also had the error when exiting.

cinematic mode works great with audio through psvr headphones. vr mode was also working minus any audio

**Comment by tzwientjuh** [comment]
How did you get your vr mode working?
And how did you setup your psvr to your pc?

**Comment by klimmiks** [comment]
I've tried Zadig to install the h264, audio and tracking drivers. Didn't help get VR mode working.

**Comment by Donlurchio** [comment]
@tzwientjuh if cinematic mode works for you then cant see why vr doesn't. I tried it with some 3d videos off youtube and apart from no audio it works fine. As for connecting to pc all you do is instead of connecting your psvr breakout box to your ps4 you connect that port to your pc, everything else is the same.
@klimmiks don't think those 3 drivers you mentioned have proper drivers yet. I don't have working drivers for them but vr mode works fine for me, I just used the driverpackage.zip that @gusmanb added at the top of this page and all runs as expected at the moment

**Comment by tzwientjuh** [comment]
@Donlurchio the headunit is connected directly to the breakout box with the hdmi and power connector. (Without the extension cord)
An hdmi cable goes from my graphics card to the 'ps4 in breakout box' and then an hdmi cable from 'tv out' to my monitor.

My monitor displays a duplicate image just fine. But when selecting vr mode, the screen in the head unit goes black and a distored image is shown on my monitor.

Keep in mind that I have an another monitor connected to my gfx card with an dvi wich displays a normal desktop screen.

Mayby I should eliminate that monitor and only use the hdmi port.

**Comment by psvr-user** [comment]
first of all: thanx for your work.
i installed the two new zip files and chose the win-usb drivers. everything seems to work fine for me (win 10 64bit) except that in "tracking and vr"-mode the movement of the headset is not recognized. is this normal?

**Comment by gusmanb** [comment]
Hey guys.

Thanks all of you for the tests, It seems we have a candidate for the drivers.

@tzwientjuh @klimmiks The behavior you explained is consistent with AMD cards, can be this your case? Ensure you are at 1920x1080 and if you use an AMD graphic card change the output pixel format to RGB 4:4:4, on the reddit thread an user has added instructions on how to do it.

@psvr-user Yeah, I know, that's because I disabled the hot keys but forgot to remove the code disabling the destruction of the classes controlling the hk, so don't worry it's normal. As the drivers and new tool seems to be working okay I will publish tomorrow a new release. Also, as I explainde to you I think, tracking enables the tracking lights, don't enables tracking as a mouse. I'm still fighting with the sensor fusion code, when I get something stable there will be new options, until you see new options, please, don't ask again the same, I know everybody wants head tracking but it's a lot more complicated than what people thinks so I need more time, we are fighting with the USB driver, the device protocol, also we seem to have found that some options are configured through HDMI instead of USB... so we have a ton of work, and we also have our regular jobs, so keep calm :)

**Comment by klimmiks** [comment]
I do have an AMD card. I'll try this tonight.

**Comment by mungewell** [comment]
I tried the portable version of 0.4 on Windows. It did not find PSVR when connected, does this still support libusb?

Will try on Linux later tonight.

**Comment by gusmanb** [comment]
@mungewell It supports LibUSB but with the new driver installer and removing the previous filters. Instead of installing a filter for LibUSB on the main composite device as we did before it now loks for the concrete interfaces, so they need the new drivers to be installed. This is the correct way to do it (on Windows, on Linux there's no composite devices, just a device with different interfaces), first of all the filter drivers are a pain to install, it works for some people, don't for others, but the installer works perfectly as far as we know, and also, as we are only targeting the correct interfaces in a future if some other interfaces became usable the filter will not interfere with these.

@klimmiks Glad to hear you got it working. About refresh, the PSVR HDMI identifies itself only as 60Hz, I had to create a custom screen mode with the nVidia drivers to achieve 90Hz and 120Hz, I think Sony decided to not to report all the refresh rates to make this compatible, the black box itself only supports 60Hz (on it's input, it outputs the correct rate for the HDM) to reduce the processing power needed to render the virtual screen and maybe if they change the EDID report on the fly when switches to VR mode that could lead to problems with devices, so this makes sense, but it's just a guess.

**Comment by berlincount** [comment]
Feels to me like most of the EDID data reported is forwarded from the attached social screen.

**Comment by mungewell** [comment]
@berlincount Please see https://github.com/gusmanb/PSVRFramework/wiki/EDIDs, and send in comments/corrections in seperate bug. Thanks,

**Comment by mungewell** [comment]
@klimmiks Regarding sound. I am documenting behaviour here https://github.com/gusmanb/PSVRFramework/issues/13

It seems that 3mm jack does not output sound (neither HDMI nor USB) unless HDMI is actively streaming. We don't yet know of a way to get any audio when HMD is in VR mode.

Please follow up on that bug if you have comment or know something new. Thanks.

**Comment by gusmanb** [comment]
@berlincount Nope, I usually do my tests without any screen attached to the box output and the EDID stills reports the same. That parts needs a lot more of work on our side as we think the HDMI is also used to control some functionality like cinematic screen locking through CEC (the box identifies itself as "Tuner 1" so sending CEC commands may affect the device behavior), after we have more advanced the USB side I will dig it.

More info in #18

**Comment by gusmanb** [comment]
Closing as the new drivers work as expected.
