### ISSUE TITLE
Command 0x15 - Solved, Individual LED brightness

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#16]
This shows a 'command 0x15' affecting the periodic report that we get from the screen dist/size setting.

What's it doing and might it be 'screen lock'?
![comand15](https://cloud.githubusercontent.com/assets/236907/20009713/2a4c606a-a26b-11e6-9cb4-04bd2afc6958.png)

**Comment by gusmanb** [comment]
Are these captures between PS4 and the headset?

**Comment by mungewell** [comment]
Yes, but not mine... I don't have a PS4 remember ;-)

From:
https://github.com/hrl7/node-psvr/issues/9

direct link:
https://drive.google.com/open?id=0B9k4M70SGKlAYWY3RVFEOVRETE0

**Comment by gusmanb** [comment]
Yes I remember, because that I asked :D

I'm implementing the report readouts to check this, I will send the 0x15 and see what happens. 

At a first glance that sent data resembles too much an ASCII string, converted yields  "FFFFP<<FF", what do you think? just a coincidence?

**Comment by gusmanb** [comment]
I have tested the command and it seems it changes the default answer, but I'm not 100% sure, there is a problem reading response reports with libusb or with the wrapper I use, I'm going to put online the RB3 with Raspbian, to check raw things like this will be a lot better to do in linux, also I can test the toolbox with it.

Could be great to be able to use the VR with a raspberry, I can think in a ton of applications like augmented reality, two cameras on the headset, a raspberry and you got augmented reality but in VR, that could be amazing XD.

**Comment by gusmanb** [comment]
Ok, I have bad news and good news, bad news I formatted the raspbian card, it has now retropie so I must reinstall to continue the tests, and I will do it next week, I'm leaving for the weekend. 
Good news is... retropie is GORGEOUS on the VR set XD. Don't know why, but it looks sharper than the PC output, the PC font gets blurry but with the RB it looks sharp, maybe it's the font type.

Oculus and Vive can have a bit more resolution, but PS VR is te only set which allows a damn raspberry to play on a cinema screen XD.

**Comment by mungewell** [comment]
figured 0x15 out; it's individual control of the LEDs. Value set for each apears to the brightness.

    # Command '0x15' can turn on/off LEDs
    #ep.write('\x15\x00\xaa\x10\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    ep.write('\x15\x00\xaa\x10\xff\x01\x46\x46\x46\x46\x50\x3c\x3c\x46\x46\x00\x00\x00\x00\x00')

    # Front Corner 4 LEDs
    ep.write('\x15\x00\xaa\x10\xff\x01\x46\x46\x46\x46\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    # Bottom Front
    ep.write('\x15\x00\xaa\x10\xff\x01\x46\x46\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    # Left front
    ep.write('\x15\x00\xaa\x10\xff\x01\x46\x00\x46\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    # Center and sides
    ep.write('\x15\x00\xaa\x10\xff\x01\x00\x00\x00\x00\x50\x3c\x3c\x00\x00\x00\x00\x00\x00\x00')
    # Just rears
    ep.write('\x15\x00\xaa\x10\xff\x01\x00\x00\x00\x00\x00\x00\x00\x46\x46\x00\x00\x00\x00\x00')

I am noticing that in my python script sometimes I have to connect/send commands twice before they get actioned. This is one of those....

**Comment by gusmanb** [comment]
Will test them tomorrow, nice finding. I suppose this report will control something else than the leds as you're setting b4/b5 always with same values.

About the need to send twice, it happened to me the first times, after I set the boot sequence as in the current code all commands work at first attempt. Anyway I will double check it with this command.

**Comment by gusmanb** [comment]
Advances, b4 & b5 are the LED mask indicating what led's to set. Here is an image with the disposition (A = b0)
![ledidentification](https://cloud.githubusercontent.com/assets/4086913/20073711/960e82d2-a52d-11e6-8777-2c73ba785c9c.png)

**Comment by mungewell** [comment]
Good work.
So you mean if I change the mask to only 'E' ('\x15\x00\xaa\x10\x10\x00...'), but set values for all LEDs, then only the face center LED will actually change?

**Comment by gusmanb** [comment]
Yep, that's right. Also allowed values for the LED's range from 0x00 to 0x80, ranges outside these values even if they're set on leds not used make the device to reject the settings.
I have it already working on the toolbox, not sure if today I will post a new release or I will wait to have the command line interface finished, if you want a test build tell me and I will upload it here.

**Comment by gusmanb** [comment]
Closing as we have this completely defined
