### ISSUE TITLE
Driver Problems

### ISSUE THREAD

**Issue by Vantec2012** [gusmanb/PSVRFramework#19]
hi there

when i try to install the winusb drivers i get error message

a problem was encountered while trying to add the drivers to the store

and when i try to use libusb 32 bit as in how to it tells me to use 64 bit and then when i do that they install but i have usb composite device in device manager with a little yellow triangle on it

then when i load toolbox it is always waiting for psvr

**Comment by tzwientjuh** [comment]
Try this [https://github.com/gusmanb/PSVRFramework/issues/12](url)
