### ISSUE TITLE
Toolbox Linux compat

### ISSUE THREAD

**Issue by gusmanb** [gusmanb/PSVRFramework#21]
I'm testing the toolbox on linux. It works itself but the commands doesn't works.

It finds the device, opens it, but when I send the set config, try to claim an interface or send data it fails miserably.

Any help with this would be highly apreciated as I never worked with libusb and Linux.

**Comment by mungewell** [comment]
A double check that your system is capable of sending commands....
https://dl.dropboxusercontent.com/u/34518077/psvr.py

Needs python USB, and then...

    $ sudo python psvr.py -h
    usage: psvr.py [-h] [-S] [-o] [-O] [-v] [-c] [-l] [-s SIZE] [-d DIST]
                   [-b BRIGHT] [-t]

    optional arguments:
      -h, --help            show this help message and exit
      -S, --shutdown        Shutdown the PSVR
      -o, --on              Turn the PSVR on
      -O, --off             Turn the PSVR off
      -v, --vrmode          Turn on VR mode, without LEDs
      -c, --cinemode        Turn on Cinematic mode, without LEDs
      -l, --leds            Set on the LEDs
      -s SIZE, --size SIZE  Set the size of the Cinematic screen
      -d DIST, --dist DIST  Set the distance of the Cinematic screen
      -b BRIGHT, --bright BRIGHT
                            Set the brightness of the screen
      -t, --test            'test' scratch pad for hacking ;-)


First thought is whether you detached the interfaces. If you dis-able the 'reattach' in the python script does your code then work?

**Comment by gusmanb** [comment]
Got it working, just had to detach the kernel driver from the interfaces prior to claiming them :). @mungewell do you have experience on creating distributable packages for linux? As this is working would be great to have redistributable packages with automatic dependencies.

**Comment by mungewell** [comment]
Don't really know about packaging... 

Closing bug as we've confirmed app works with mono on Linux.
