### ISSUE TITLE
Option to translate tracking into mouse movements

### ISSUE THREAD

**Issue by Frogburt** [gusmanb/PSVRFramework#22]
Excellent work gusmanb.
Would it be possible to enhance the PSVRFramework to allow tracking to be translated into mouse movements?
I know there are alternative apps that claim to do this but they don't work for me, probably because I am using Microsoft's WinUSB drivers.
Your app is looking like it will be the all-in-one solution.

**Comment by gusmanb** [comment]
Closing as this has been answered a ton of times. We're working on it, on a future if all goes ok it will have this option.
