### ISSUE TITLE
Command 0x21 - Bad Side Tone Value

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#23]
Interesting, that it spews ASCII..

    ep.write('\x21\x00\xaa\x10\xC0\x32\x23\x20\x00\x00\x00\x00\x00\x00\x20\x22\x22\x22\x01\x00')
responds

    00000000  a0 00 aa 3c 21 04 52 2d  49 44 20 30 78 32 31 3a  |...<!.R-ID 0x21:|
    00000010  20 42 61 64 20 73 69 64  65 74 6f 6e 65 20 76 61  | Bad sidetone va|
    00000020  6c 75 65 20 5b 33 34 5d  00 00 00 00 00 00 00 00  |lue [34]........|
    00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

**Comment by mungewell** [comment]
in fact the maximum values which don't cause this error are:

    ep.write('\x21\x00\xaa\x10\xC0\x64\x32\xff\xff\xff\xff\xff\xff\xff\x20\x05\x04\x02\x01\xff')

Which means we have a few more mystical bytes after the 0x20 to work out.

**Comment by gusmanb** [comment]
Hmmm, the side tone value is b15 which ranges from 0 to 5, that's the mic feedback, are you sure the other bytes (except b18 which is the one that resets the VR mode) do something?

After I implement the command line interface I will add to the wiki all the reports we know as we need somewhere to see what we already found.

**Comment by mungewell** [comment]
Regarding extra bytes; I am only sure that they cause this error message if set higher than 4, 2, and 1 respectively.
I shall wear an imaginary deerstalker (https://en.wikipedia.org/wiki/Deerstalker#Sherlock_Holmes) whilst attempting to figure out what they do.

**Comment by gusmanb** [comment]
Don't forget your pipe ;)

I will play with them tomorrow, today I need to work or I will get fired XD.

**Comment by mungewell** [comment]
Closing as we've figured these...
