### ISSUE TITLE
Direction of our efforts

### ISSUE THREAD

**Issue by gusmanb** [gusmanb/PSVRFramework#24]
After watching the impressive progress of the PSMoveService guys and having nearly arrived to an agreement to make our toolbox and the move service compatibles I belive we can stop fighting with the sensor data and concentrate on the USB and HDMI protocol, let our efforts go to control the system and the team at PSMoveService concentrate on controlling the input data.

Does this sound right to you?

Any opinion is welcome.

**Comment by cercata** [comment]
That's Cool and Wise.

And an agreement doesn't avoid you to give them a hand sometimes with sensor data, or receiving a hand from them with controling the headset.

By the way, what are those "impresive progress" made by them ?

**Comment by gusmanb** [comment]
Look at this: https://www.youtube.com/watch?v=V3E718_FwyE

**Comment by mungewell** [comment]
My view on direction is:
1). Be the lead source of information on the PSVR, how it interfaces to PC and how to drive it.
2). Provide a small/concise util for switching between Cinematic/VR modes, with a little adjust where needed.
3). Provide simple Orientation (rotation only) tracking for simple viewers/gaming/etc. for example with 'mouse view direction control'.

We're already hitting 1) and 2). :-)

The last on is tricky, I think that 'we' should NOT attempt to be everything. However PSMoveService is not simple to set up and calibrate. A small util which is 'plug and play' would be very useful in getting people working with PSVR - albeit limited to 3D videos and non VR-ready applications. For full on apps they can write their own code with information we're sharing.
https://www.youtube.com/watch?v=XiLYa1EZL04

As you can probably sense from my postings, I'm all about learning/teaching/enabling...

**Comment by MaVe-64** [comment]
It's only the position tracking part of PSMoveservice that's not simple to setup (with the PS3 camera's). Calibration of the motion sensors would be very easy, so PSMoveservice use with only motion tracking would be a good solution to get easy & fast VR working (3 degrees of freedom).

BTW, Riftcat is considering adding a solution in VRidge to port the SteamVR output to HDMI. Let's hope so, that would be great!

**Comment by electromat94** [comment]
@mungewell is right. You did a lot of good hard work and the results are great! I'm playing Farming Simulator 17 with the PSVR and your Toolbox. I play it with cinematic mode who is better than VR mode + Tridef3D . But all is missing is the headtracking.(would be nice to have a shortcut to enable mouse-tracking while in cinematic mode) That guy who made the mouse-headtracking software used the gyro on PSVR (you already know). But it is working (even with slow movement of the head) . Anyway I support you in every way you'll take and thanks a lot for all the effort, considering job/family/free time (!)

**Comment by gusmanb** [comment]
Ok, I think we have a clear path for development: 

1-Stick developing the protocol and control of the device as our primary goal.
2-When we have something what we consider a full and stable control implement a mouse emulator with the sensor data (with the help of HipsterSloth if possible)
3-Add options to make this compatible with PSMoveService (option to disable sensor interface, expose a command line interface so PSMoveService and other programs can control the HDM without messing with USB)

**Comment by cercata** [comment]
Nice.

Why CLI instead of a SO/DLL interface ?
CLI could be done based on the DLL.

Anyway, while it's opensource, someone else can do a DLL if they want.

**Comment by gusmanb** [comment]
A SO/DLL interface would require a compilation for each operating system, is more "complicated" to program, would need to be done in C or C++ while all the FW is programmed in C# and would not be accessible to all languages.

Said that, it's already implemented and it comes in two flavors, UDP listener and CLI. UDP is universal, any language has support for it and is easy to program, and CLI is accessible even for batch or shell scripts, so this way anyone can choose what prefer to use.

https://github.com/gusmanb/PSVRFramework/wiki/Toolbox-network-commands-and-command-line-parameters

I will try to cerate a release today.
