### ISSUE TITLE
Cmd Fuzzing - 'Bad  R-ID' and 'Bad Length'

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#28]
Seems the ASCII errors will tell you even more...

    ep.write('\x19\x00\xaa\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    a000aa3c190142616420522d49442031
    39000000000000000000000000000000
    00000000000000000000000000000000
    00000000000000000000000000000000
    $ echo -n a000aa3c190142616420522d49442031 | xxd -r -p| hexdump -c
    0000000   �  \0   �   < 031 001   B   a   d       R   -   I   D       1

    ep.write('\x23\x00\xaa\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    a000aa3c2303522d494420307832333a
    20426164206c656e6774682031365b34
    5d000000000000000000000000000000
    00000000000000000000000000000000
    $ echo -n 20426164206c656e6774682031365b34 | xxd -r -p| hexdump -c
    0000000       B   a   d       l   e   n   g   t   h       1   6   [   4

**Comment by gusmanb** [comment]
Nice, for what I see b3 may be response code (3C=error?), b4 is report ID, b5 is error code (0x01 = report id error, 0x03=bad length) and the rest of the packet is a null terminated string. Adding it now to the fw as this can be really helpful on the tests.

**Comment by gusmanb** [comment]
Ok, no, b3 is data length and b5 is result code, 0x00 = OK, 0x01= unknown report, 0x03 = wrong report length

**Comment by gusmanb** [comment]
This is a lot more interesting than I thought. This is not a report response, it's like "unsolicited data" related to reports, any message with info from the device to the station. When I turn on/off the headset, depending on the headset status (screen on/ off, VR or cinematic, HDMI signal or not) it also reports the 0x17 and 0x15 reports as OK, maybe it internally changes the values of these reports and it signals this change?
Going to do a bruteforce to all reports and check if something interesting arises.

**Comment by gusmanb** [comment]
This is the list of reports with answers:

0x11, 8 bytes, VR + tracking? doesn't makes sense, testing
0x13, 4 bytes, box power off
0x15, 16 bytes, led settings
0x17, 4 bytes, headset power
0x1B, not in non-vr mode?, unknown
0x21, 16 bytes, configuration
0x23, 4 bytes, switch mode
0x81, 8 bytes, unknown

So we have left 0x11 (doesn't makes sense to switch to VR mode and light up leds sending FFFFFF00, testing a bruteforce to these values), 0x1B (not in VR mode? I did this in cinematic!) and 0x81.

**Comment by mungewell** [comment]
Closing as I think we understand most commands, apart from cmd 0x1b (opened new bug).
