### ISSUE TITLE
Release 0.4.5 - no window shown on Linux

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#31]
Attempting to run 0.4.5 portable on Linux with Mono.

Un-RAR'ed to a directory and run as:

    xubuntu@xubuntu:~/psvr$ mono PSVRToolbox.exe
    Could not set X locale modifiers
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB

I see a brief flash of a window, and then nothing. :-(

Thought might be running minimized, so copied 'settings.json' from previous Windows install - with no joy. It does appear to still be running (according to 'ps ax'), I just can't see it.

Are there any command line options to prevent 'run minimized'?

**Comment by mungewell** [comment]
This might be due to version of Mono I guess... I have the current from Ubuntu repo's

    mono-runtime_4.2.1.102+dfsg2-7ubuntu4_amd64.deb
    mono-runtime-common_4.2.1.102+dfsg2-7ubuntu4_amd64.deb

**Comment by gusmanb** [comment]
Previous version did work for you? mono-runtime only offers the most limited support for mono without the WinForms libraries, to work you need mono-complete, not mono-runtime. It should work, I tested it on the RB, but I have mono 4.6.

If you can confirm the previous version did work for you I can edit the images used on the app, may be the libpng version you have doesn't like the image format I used. My libpng version is 1.2.50.

**Comment by gusmanb** [comment]
Also, there is a setting on the settings.json to control if the app must run minimized, it's named "StartMinimized" and can be true or false.

**Comment by gusmanb** [comment]
Ok, I've solved some minor problems with the interface on Linux and used pngcrush to remove the PNG problem, it seems libpng has become more restrictive on version 1.6 and that's why that message appears (but it should not stop the app from running). One last (stupid) note, if you run the app from command line you must left it open, it doesn't "dettaches" from the console process. I also have added an script to run the app silently.

Can you test it?
[PSVRToolbox.zip](https://github.com/gusmanb/PSVRFramework/files/587114/PSVRToolbox.zip)

**Comment by mungewell** [comment]
Yes, this is same behavior as previous versions, even if I 'apt-get install mono-complete'. A brief flash of a window and then nothing. I'll also note that the 'settings.json' is not created, so the code isn't getting to that point.

    mono-complete_4.2.1.102+dfsg2-7ubuntu4_amd64.deb

I'm running tests on top of the xubuntu bootable USB, so fairly easy to recreate... just take a copy of the '.debs' (from '/var/cache/apt/archives/') so you don't have to download them every boot.

    xubuntu@xubuntu:~/test$ unzip /cdrom/mono_test/PSVRToolbox_20161112.zip
    Archive:  /cdrom/mono_test/PSVRToolbox_20161112.zip
      inflating: Gma.System.MouseKeyHook.dll
      inflating: LibUsbDotNet.dll
      inflating: MACTrackBarLib.dll
      inflating: Newtonsoft.Json.dll
      inflating: Newtonsoft.Json.xml
      inflating: PSVRFramework.dll
     extracting: PSVRToolbox
      inflating: PSVRToolbox.exe
    xubuntu@xubuntu:~/test$ ls
    Gma.System.MouseKeyHook.dll  Newtonsoft.Json.dll  PSVRToolbox
    LibUsbDotNet.dll             Newtonsoft.Json.xml  PSVRToolbox.exe
    MACTrackBarLib.dll           PSVRFramework.dll
    xubuntu@xubuntu:~/test$ ./PSVRToolbox
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: cHRM chunk does not match sRGB

    xubuntu@xubuntu:~/test$ ls
    Gma.System.MouseKeyHook.dll  Newtonsoft.Json.dll  PSVRToolbox
    LibUsbDotNet.dll             Newtonsoft.Json.xml  PSVRToolbox.exe
    MACTrackBarLib.dll           PSVRFramework.dll
    xubuntu@xubuntu:~/test$ ps ax | grep -i psvr
     2928 pts/6    Sl     0:00 mono PSVRToolbox.exe
     2941 pts/6    S+     0:00 grep --color=auto -i psvr

**Comment by gusmanb** [comment]
By default it will not create the json unless you change anything, if the settings file doesn't exists the app loads a default config in memory and it persists the values only if you change something. Maybe the app is minimized as a tray icon?

I will download today a xubuntu live cd and try to check this.

**Comment by gusmanb** [comment]
Ok, there is a problem with XFCE and tray icons, it happens not just for mono but for other apps like Skype so I changed the behavior on Linux, it will not totally hide, just gets minimized.

Also, the problem with the libpng did not happened to me, are you sure you tested the 0.4.5 version? Maybe I uploaded the wrong package, not sure, try the new one.

**Comment by mungewell** [comment]
I'll retest tonight with your new 0.6 release....

pretty sure it was the right version, Perhaps it would help to have revision number in zip file name, or a text file within the zip with revision history.

**Comment by mungewell** [comment]
Fixed in 0.4.6, still starts minimized but visible on toolbar. Need to run as root (ie 'sudo ./runtoolbox.sh') to connect to PSVR, but it does work.

Closing bug.
