### ISSUE TITLE
Cmd 0x1B - Not in non-VR Mode?

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#32]
Try to work out why it errors... does 'VR mode' mean 'VR Audio mode'?

    a000aa3c
    1b64522d494420307831423a204e6f74 =1BdR-ID 0x1B: Not
    20696e206e6f6e2d5652206d6f64652e  in non-VR mode.
    00000000000000000000000000000000 =00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00
    000000000000000000000000 =00=00=00=00=00=00=00=00=00=00=00=00

**Comment by gusmanb** [comment]
Maybe VR mode means just having the HMD on? Will try this tomorrow.

**Comment by mungewell** [comment]
Tried that, no better.

Maybe this this a firmware update command and needs to be booted in some minimal mode - just a random guess.

**Comment by mungewell** [comment]
The 'not in non-vr mode' refers to cinematic mode with the gamepad icon....
https://github.com/gusmanb/PSVRFramework/issues/33
