### ISSUE TITLE
Programm for sensor braodcast or use the sensor

### ISSUE THREAD

**Issue by Liriel-666** [gusmanb/PSVRFramework#34]
you have unter options a setting for Sensor Broadcast.
with wich program works this broadcast.

or which programm can youse the sensor when "enable tracking and VR"

**Comment by gusmanb** [comment]
Sensor broadcast is not intended for any concrete program, it broadcasts UDP packets containing JSON objects, any program willing to use it needs to listen on the configured port and use these JSON objects.

The enable tracking activates the headset lightning for any tracking system which wants to use it, does nothing else.

**Comment by Liriel-666** [comment]
ah ok thx.
no using of the intern sensor at the momen when i understand it

**Comment by gusmanb** [comment]
No, it uses the sensor data, the JSON broadcasted objects contains the RAW sensor data from the HMD.

Also, i recommend you to follow the progess on [PSMoveService](https://github.com/cboulay/PSMoveService), they're doing huge advances on head tracking with PSVR.
