### ISSUE TITLE
VR Player - supported formats?

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#5]
Which file formats/image formats does the VR player support?

Got any 'wow' recommendations?
Simon

**Comment by gusmanb** [comment]
@mungewell It uses VLC, so, as far as I know, every video format (but I restricted it for now to MP4, any encoding), for 3D type must be side-by-side 180º.

For test, here is the video I used (the ones with best quality I found are pr0n and programming while you have a boner is not very funny XD) : https://www.reddit.com/r/oculus/comments/1on60b/a_high_resolution_180_degree_stereoscopic_music/

Beware, view angle is unrestricted, you will see the "ugliness" of the normal mapping. I need to recreate that damn sphere, Lightwave 3D is very good, but when comes to spherical normal mappings it does very strange things.
