### ISSUE TITLE
EDID - why has it changed?

### ISSUE THREAD

**Issue by mungewell** [gusmanb/PSVRFramework#8]
Bizarrely the EDID that my PSVR seems to have changed slightly. This PSVR has never been plugged into PS4 so it's not something that Sony could have actioned.

From Sat, Oct 29th:
>00000000  00 ff ff ff ff ff ff 00  4d d9 03 b4 01 01 01 01  |........M.......|
>00000010  30 18 01 03 80 10 09 78  0a 3d a5 a9 56 3d b6 22  |0......x.=..V=."|
>00000020  0c 50 54 20 00 00 d1 c0  01 01 01 01 01 01 01 01  |.PT ............|
>00000030  01 01 01 01 01 01 02 3a  80 18 71 38 2d 40 58 2c  |.......:..q8-@X,|
>00000040  45 00 a0 5a 00 00 00 1e  d6 09 80 a0 20 e0 2d 10  |E..Z........ .-.|
>00000050  10 60 a2 00 a0 5a 00 00  00 18 00 00 00 fc 00 53  |.`...Z.........S|
>00000060  43 45 49 20 48 4d 44 20  2a 30 38 0a 00 00 00 fd  |CEI HMD *08.....|
>00000070  00 17 3d 1a 44 0f 00 0a  20 20 20 20 20 20 01 d0  |..=.D...      ..|
>00000080  02 03 25 f0 4c 90 1f 05  14 20 04 13 02 03 11 12  |..%.L.... ......|
>00000090  01 23 09 07 07 83 01 00  00 68 03 0c 00 11 00 00  |.#.......h......|
>000000a0  1e 0f e2 00 6a 00 00 00  00 00 00 00 00 00 00 00  |....j...........|
>000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>*
>000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 b3  |................|

From Tue, Nov 1st: 
>00000000  00 ff ff ff ff ff ff 00  4d d9 03 b4 01 01 01 01  |........M.......|
>00000010  30 18 01 03 81 46 27 78  0a 3d a5 a9 56 3d b6 22  |0....F'x.=..V=."|
>00000020  0c 50 54 20 00 00 d1 c0  01 01 01 01 01 01 01 01  |.PT ............|
>00000030  01 01 01 01 01 01 02 3a  80 18 71 38 2d 40 58 2c  |.......:..q8-@X,|
>00000040  45 00 a0 5a 00 00 00 1e  d6 09 80 a0 20 e0 2d 10  |E..Z........ .-.|
>00000050  10 60 a2 00 a0 5a 00 00  00 18 00 00 00 fc 00 53  |.`...Z.........S|
>00000060  43 45 49 20 48 4d 44 20  2a 30 38 0a 00 00 00 fd  |CEI HMD *08.....|
>00000070  00 38 3d 20 44 0f 00 0a  20 20 20 20 20 20 01 54  |.8= D...      .T|
>00000080  02 03 23 70 4a 90 1f 05  14 20 04 13 03 12 01 26  |..#pJ.... .....&|
>00000090  15 07 50 09 07 01 83 01  00 00 68 03 0c 00 21 00  |..P.......h...!.|
>000000a0  00 1e 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>*
>000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 2c  |...............,|
>00000100

The difference is in the audio section, it _now_ supports AC3 audio... strange.
[bus7_poweron_1080p_decode.txt](https://github.com/gusmanb/PSVRFramework/files/568300/bus7_poweron_1080p_decode.txt)
[edid_psvr_decode.txt](https://github.com/gusmanb/PSVRFramework/files/568302/edid_psvr_decode.txt)

**Comment by gusmanb** [comment]
So one of the settings but must have activated it... maybe byte 14?

**Comment by gusmanb** [comment]
@mungewell may be the reports where one in cinematic mode and other in vr mode? when it gets to VR mode I detected the audio gets off as it enables the 3D audio interface, so maybe it changes de HDMI mode and then accepts AC3 instead oc PCM, just a guess.

**Comment by mungewell** [comment]
I have a theory. At weekend I was stand alone, Tues I had TV connected for social screen. Will checkout whether this is the cause for variance.

**Comment by gusmanb** [comment]
Yeah, that would also make sense, if the TV supports AC3 then it may change
it's edid to stream the audio data with the proper format.

2016-11-03 20:02 GMT+01:00 mungewell <notifications@github.com>:

**Comment by mungewell** [comment]
Confirmed. EDID changes according 'Social Screen' device.

Closing out bug,
